### ISSUE TITLE
Quest Tunics!

### ISSUE THREAD

**Issue by impeeza** [capsterx/solarus#2]
Hi, The quest Tunics! (https://www.solarus-games.org/en/games/tunics) make no use of the joy-pad, only use keyboard for playing and selection menu,  by now the engine only let you to enter on a new game but once inside you can't move anywhere and only respond to [A] button using the sword but nothing more.

thanks for you help.

**Comment by capsterx** [comment]
I am able to both start and move in the tunics game, are you using https://github.com/capsterx/solarus/releases/tag/v0.4-luajit-1.6.4 ?

**Comment by capsterx** [comment]
sorry, https://github.com/capsterx/solarus/releases/tag/v0.4.1-luajit

**Comment by capsterx** [comment]
ok, sorry again, https://github.com/capsterx/solarus/releases/tag/v0.4.2-luajit

**Comment by impeeza** [comment]
Hi he he he,  I was using solarus-v0.4.0-luajit-1.6.4, update to solarus-v0.4.2-luajit-1.6.4 and now I can move around interact and use the sword, however no controller button are mapped to keys [A] or [D] so you can't use any item, this game is a little quirk 😸  a suggestion will be a menu (or ini file) to configure mapping between controller buttons and keyboard inputs so you can customize any game.

Thanks a lot for all your great work.

**Comment by capsterx** [comment]
That should be easy enough for me to do, my later ports all use common code that allows one to configure the mappings, this predates that but I should be able to upgrade it to the common code.  I'd have to think about if I can make it per-game or not, probably can.

**Comment by impeeza** [comment]
Thank man for all your work 👍

**Comment by impeeza** [comment]
With the latest version of Solarus, you can map the joy buttons to keyboard entries so the game is fully playable.  thanks a lot for all your effort
